[bot]
owner_tg_id = 123456789
token = "token"
drop_pending = true
use_webhook = false
use_class_middlewares = true
actions_timeout = 0.2
page_size = 10

logger.name = "BotLogger"
logger.level = "INFO"
logger.stream = "stdout"
logger.file_path = "logs/bot.log"
logger.format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# allowed_updates = [...] or "ALL"

state_storage.type = "redis"
state_storage.redis.host = "localhost"
state_storage.redis.port = 6379
# state_storage.redis.db = 0
# state_storage.redis.password = "password"
# state_storage.redis.prefix = "prefix"

webhook.url = "webhook_url"
webhook.secret_token = "secret token"
# webhook.cert_path = "cert_path"
# webhook.ip_address = "ip_address"
# webhook.max_connections = 40

# telegram_api_url = "telegram_api_url"

[db]
host = "localhost"
port = 5432
user = "user"
password = "password"
database = "database"

logger.name = "DBLogger"
logger.level = "INFO"
logger.stream = "stdout"
logger.file_path = "logs/db.log"
logger.format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# [extra sections if any]
# ...

[logger]
name = "FairLogger"
level = "INFO"
stream = "stdout"
file_path = "logs/fair.log"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[messages]
welcome = "Welcome"
unregistered_help = "Unregistered help"
player_help = "Player help"
manager_help = "Manager help"
owner_help = "Owner help"
anti_flood = "Anti flood"
get_player_name = "Get player name"
invalid_player_name = "Invalid player name"
player_name_already_taken = "Player name already taken"
player_registered = "Player registered"
player_balance = "Player balance {}"
choose_money_transfer_recipient = "Choose money transfer recipient"
money_transfer_recipient_cancelled = "Money transfer recipient cancelled"
choose_money_transfer_amount = "Choose money transfer amount"
money_transfer_success = "Money transfer success"
choose_new_queue_location = "Choose new queue location"
new_queue_location_cancelled = "New queue location cancelled"
queue_entry_added = "Queue entry added"
player_queue_location = "Player queue location {} - {}"
player_left_queue = "Player left queue"
manager_registration_forbidden = "Manager registration forbidden"
manager_registration_disabled = "Manager registration disabled"
get_manager_password = "Get manager password"
get_manager_name = "Get manager name"
invalid_manager_name = "Invalid manager name"
manager_name_already_taken = "Manager name already taken"
manager_registered = "Manager registered"
all_players= "All players"
all_players_cancelled= "All players cancelled"
all_locations= "All locations"
all_locations_cancelled= "All locations cancelled"
choose_add_balance_recipient= "Choose add balance recipient"
add_balance_cancelled= "Add balance cancelled"
choose_add_balance_amount= "Choose add balance amount"
choose_subtract_balance_recipient= "Choose subtract balance recipient"
subtract_balance_cancelled= "Subtract balance cancelled"
choose_subtract_balance_amount= "Choose subtract balance amount"
choose_reward_recipient= "Choose reward recipient"
reward_cancelled= "Reward cancelled"
choose_reward_amount= "Choose reward amount"
reward_successful= "Reward successful"
choose_purchase_recipient= "Choose purchase recipient"
purchase_cancelled= "Purchase cancelled"
choose_purchase_amount= "Choose purchase amount"
purchase_successful = "Purchase successful"
choose_location= "Choose location"
choose_location_cancelled = "Choose location cancelled"
location_updated = "Location updated"
chosen_location = "Chosen location {}"
my_location_queue = "My location queue"
my_location_queue_cancelled = "My location queue cancelled"
location_player_chosen_options = "Location player chosen options"
location_paused = "Location paused"
location_unpaused = "Location unpaused"
manager_my_location= "Manager my location {} - {}"
manager_left_location= "Manager left location"
add_player_error = "Add player error"
player_not_found_error = "Player not found error"
player_not_in_queue_error = "Player not in queue error"
queue_entry_already_exists_error = "Queue entry already exists"
money_transfer_recipient_not_chosen_error = "Money transfer recipient not chosen error"
money_transfer_amount_invalid_error = "Money transfer amount invalid error"
add_manager_error = "Add manager error"
manager_not_on_location_error= "Manager not on location error"
bad_location_error = "Bad location error"
pause_location_error = "Pause location error"
unpause_location_error = "Unpause location error"
bad_player_balance_error = "Bad player balance error"
bad_chosen_player_error = "Bad chosen player error"
bad_manager_error = "Bad manager error"
add_user_error = "Add user error"
add_tg_account_error = "Add telegram account error"
unknown_error = "Unknown error"

[buttons]
reg_player = "Register as player"
reg_manager = "Register as manager"
new_queue = "New queue"
my_balance = "My balance"
transfer_money = "Transfer money"
my_queue = "My queue"
leave_queue = "Leave queue"
list_all_players = "List all players"
list_all_locations = "List all locations"
add_balance = "Add balance"
subtract_balance = "Subtract balance"
choose_location = "Choose location"
reward_player = "Reward player"
purchase = "Purchase"
my_location = "My location"
my_location_queue = "My location queue"
leave_location = "Leave location"
pause_location = "Pause location"
unpause_location = "Unpause location"
prev_page = "<<"
next_page = ">>"
help = "Help"
cancel = "Cancel"
